# Model arguments
model_name_or_path: /grp01/cs_yzyu/wushuai/model/r1-distill/DeepSeek-R1-Distill-Llama-8B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: /grp01/cs_yzyu/wushuai/deep_r1/data/open-r1/OpenR1-Math-220k
dataset_configs:
- default
dataset_num_proc: 48

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: 'no'
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Llama-8B-Handsome-Distill
hub_strategy: end
learning_rate: 5.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: true
max_seq_length: 16384
max_steps: -1
num_train_epochs: 1
output_dir: results/sft/DeepSeek-R1-Distill-Llama-8B
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 1
push_to_hub: False
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
use_liger: true
warmup_ratio: 0.05